Replace non-breaking space characters in code snippets
Some of the sketch code was littered with random use of the non-breaking space character in place of standard space characters. Although the two characters appear the same to a human, they are not the same to the compiler, and so cause spurious errors when the sketch was compiled:

```
sketch_nov15a.ino:3:1: error: stray '\302' in program
     // initialize digital pin LEDR as an output.
 ^
sketch_nov15a.ino:3:2: error: stray '\240' in program
     // initialize digital pin LEDR as an output.
  ^

exit status 1

Compilation error: stray '\302' in program
```

The solution is to replace these invalid characters with standard spaces