Correct `MKRIoTCarrier::display.print` snippets
Previously the `carrier` object component of the statement was missing from the code snippets demonstrating the use of
the "Arduino_MKRIoTCarrier" library's `MKRIoTCarrier::display.print` function. This would cause compilation of the
snippet to fail:

error: 'display' was not declared in this scope
   display.print("text");
   ^~~~~~~